# Site settings
name: Michelle Jamieson
title: Michelle K Jamieson | Researcher & Creative
description: Research Psychologist and Creative
url: https://themichjam.github.io/
baseurl: ''
email: rmkjamieson@gmail.com
cover: https://themichjam.github.io/img/og.png
logo: https://themichjam.github.io/img/emojis/technologist.png
resume: https://themichjam.github.io/resume.pdf
social:
  - title: email
    url: mailto:hellomichjam@gmail.com
  - title: twitter
    url: https://twitter.com/themichjam
  - title: instagram
    url: https://instagram.com/themichjamm
  - title: github
    url: https://github.com/themichjam
  - title: linkedin
    url: https://www.linkedin.com/in/michellekjamieson
  - title: YouTube
    url: https://www.youtube.com/channel/UCA9g_B5hzqVul6LHzAL4NYA/featured

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
